const sirenitaData = [
    { id: 1, nombre: "Ariel", descripcion: "La protagonista, una sirena curiosa y aventurera.", imagen: "https://i.postimg.cc/4xj8jR8P/1.png" },
    { id: 2, nombre: "Sebastián", descripcion: "Un cangrejo amigo de Ariel.", imagen: "https://i.postimg.cc/jS6wYzc1/2.png" },
    { id: 3, nombre: "Flounder", descripcion: "El pez amigo de Ariel.", imagen: "https://i.postimg.cc/Jn0GXS8w/3.png" },
    { id: 4, nombre: "Ursula", descripcion: "La villana, una bruja del mar.", imagen: "https://i.postimg.cc/DftP2PQf/4.png" },
    { id: 5, nombre: "Rey Tritón", descripcion: "El padre de Ariel, rey del mar.", imagen: "https://i.postimg.cc/LsCjGt6p/5.png" },
    { id: 6, nombre: "Príncipe Eric", descripcion: "El amor de Ariel.", imagen: "https://i.postimg.cc/LXGL8m1Q/6.png" },
    { id: 7, nombre: "Scuttle", descripcion: "Una gaviota amiga de Ariel.", imagen: "https://i.postimg.cc/qvpnRbNr/7.png" },
    { id: 8, nombre: "Flotsam", descripcion: "Uno de los secuaces de Úrsula.", imagen: "https://i.postimg.cc/tJhZRWy7/8.png" },
    { id: 9, nombre: "Jetsam", descripcion: "Uno de los secuaces de Úrsula.", imagen: "https://i.postimg.cc/tJhZRWy7/8.png" },
    { id: 10, nombre: "Max", descripcion: "El perro del Príncipe Eric.", imagen: "https://i.postimg.cc/MKmMh7dF/10.png" },
    { id: 11, nombre: "Grimsby", descripcion: "El mayordomo del Príncipe Eric.", imagen: "https://i.postimg.cc/x1jJYXZT/11.png" },
    { id: 12, nombre: "Carreta", descripcion: "El carruaje del Príncipe Eric.", imagen: "https://i.postimg.cc/65tTL7tL/12.png" },
    { id: 13, nombre: "Sirenas", descripcion: "Las hermanas de Ariel.", imagen: "https://i.postimg.cc/sg0XrwSw/13.png" },
    { id: 14, nombre: "Atlantica", descripcion: "El reino submarino.", imagen: "https://i.postimg.cc/KztvtbWH/14.png" },
    { id: 15, nombre: "Castillo", descripcion: "El castillo del Príncipe Eric.", imagen: "https://i.postimg.cc/RhRSbR41/15.png" },
    { id: 16, nombre: "Barco", descripcion: "El barco del Príncipe Eric.", imagen: "https://i.postimg.cc/FFgHR93f/16.png" },
    { id: 17, nombre: "Flujo", descripcion: "La corriente marina.", imagen: "https://i.postimg.cc/FFgHR93f/16.png" },
    { id: 18, nombre: "Tormenta", descripcion: "Una tormenta en el mar.", imagen: "https://i.postimg.cc/FFgHR93f/16.png" },
    { id: 19, nombre: "Baile", descripcion: "El baile en el castillo.", imagen: "https://i.postimg.cc/XYhVhXSP/19.png" },
    { id: 20, nombre: "Lago", descripcion: "El lago donde Ariel y Eric pasean.", imagen: "https://i.postimg.cc/tC4p4F9f/20.png" },
    { id: 21, nombre: "Anillo", descripcion: "El anillo del Príncipe Eric.", imagen: "https://i.postimg.cc/MTLbfyhD/21.png" },
    { id: 22, nombre: "Tesoro", descripcion: "El tesoro de Ariel.", imagen: "https://i.postimg.cc/gj6yVxpP/22.png" },
    { id: 23, nombre: "Cueva", descripcion: "La cueva de Úrsula.", imagen: "https://i.postimg.cc/ryd7ngFq/23.png" },
    { id: 24, nombre: "Pozo", descripcion: "El pozo mágico.", imagen: "https://i.postimg.cc/05LFLmbD/24.png" },
    { id: 25, nombre: "Navegación", descripcion: "La navegación en el mar.", imagen: "https://i.postimg.cc/FFgHR93f/16.png" },
];
